baseURL = "https://saresamadou.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Samadou SARE"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Hi there, I'm Samadou"
author = "Samadou SARE"
copyright = "2020-2021"
description = """
A passionated software crafmanship developper.
I hope you like stories.I propose you to learn software development concepts by reading a short story."
"""
profilePicture = "images/profile.jpeg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
# postSectionName = "blog"
fullPostContent = false

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/aboudou-samadou-sare-5b267a62/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/saresamadou"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "aboudou.samadou.sare@gmail.com"

## Menu items

[menu]

[[Languages.en.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[Languages.en.menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.en.menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"

[Languages]
[Languages.en]
title = "My blog"
weight = 1
LanguageName = "English"
description = "Website of Samadou SARE"


[Languages.fr]
title = "Mon blog"
description = "Siteweb de Samadou SARE"
weight = 2
LanguageName = "Français"

